FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

# Enable bytecode compilation and Python optimization
ENV UV_COMPILE_BYTECODE=1
ENV PYTHONOPTIMIZE=1
ENV UV_LINK_MODE=copy

# Set Python path to include the src directory for imports
ENV PYTHONPATH="/app/src:$PYTHONPATH"
# ENV PYTHONPATH="/app/src"

# Copy only dependency files first for better layer caching
COPY pyproject.toml uv.lock ./

# Install dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen

# Change: Copy API code
COPY src/api ./src/api/

# Change: Pre-compile Python files to bytecode
RUN python -m compileall ./src/api

# Set PATH to use the virtual environment
ENV PATH="/app/.venv/bin:$PATH"


# # Create non-root user and set permissions, adduser --home /app
RUN addgroup --system app && \
    adduser --system --ingroup app app && \
    chown -R app:app /app
# RUN addgroup --system app && \
#     adduser --system --ingroup app --home /app app && \
#     chown -R app:app /app

# Switch to non-root user
USER app

# Change: FastAPI port
EXPOSE 8000

# Command to run the application
# uvicorn is a server that FastAPI uses to run the application
# it takes actual runnable application and runs it with parameters (host and port)
# reload is to restart the server when code changes
CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]